---
title: "Logistic Regression on Titanic Survival (R)"
author: "Shunji Wei"
date: "2019/7/15"
output: html_document
---

```{r}
# Loading data
titanic = read.csv('~/Downloads/Titanic_train.csv')

# View the first few rows of data
head(titanic)[, c(1:3,5:8,10)]
```

```{r}
# Decode Sex: 'male' as 1 and 'female' as 0
titanic$Sex = (titanic$Sex == 'male')*1

# Subset the data including the columns we want
titanic_sub = subset(titanic,select = c(Survived,Pclass, Sex, Age, SibSp, Parch, Fare))

# Data Summary
summary(titanic_sub)
```

```{r}
# 2-way contingency table 
xtabs(~ Survived + Pclass, data = titanic_sub)
```

```{r}
# Missing values 
titanic_sub$Age[is.na(titanic_sub$Age)] = mean(titanic_sub$Age[!is.na(titanic_sub$Age)])

# Split training set and test set
train_set = titanic_sub[1:802, ]
test_set = titanic_sub[803:891, ]
```

```{r}
# Set the class of Pclass and Sex as factor
train_set$Pclass = as.factor(train_set$Pclass)
train_set$Sex = as.factor(train_set$Sex)

# Fit the Logistic model
logit_fit = glm(Survived ~ ., data = train_set, family = "binomial")
summary(logit_fit)

# Provide the confidence interval
ci = confint.default(logit_fit)
```


```{r}
# Predicting
test_set$Pclass = as.factor(test_set$Pclass)
test_set$Sex = as.factor(test_set$Sex)

surv_prob = predict(logit_fit, newdata = test_set, type = 'response')
head(surv_prob)

# Model Evaluation by error rate
mean(round(surv_prob) != test_set$Survived)
```

